# Generated by Django 5.1.6 on 2025-02-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyallocation',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='The amount to allocate (must be greater than zero).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
