# Generated by Django 5.1.6 on 2025-02-26 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_moneyallocation_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyallocation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
